export {}
declare global {
  const $: typeof import('jquery')['default']
  const Key: typeof import('ts-key-enum')['Key']
  const Trans: typeof import('@complexity/i18n')['Trans']
  const TransWithPrefix: typeof import('@complexity/i18n')['TransWithPrefix']
  const cn: typeof import('@/utils/cn')['cn']
  const createContext: typeof import('react')['createContext']
  const deepEqual: typeof import('@/utils/deep-equal')['deepEqual']
  const extendT: typeof import('@complexity/i18n')['extendT']
  const invariant: typeof import('@/utils/utils')['invariant']
  const isExtensionContext: typeof import('@/utils/utils')['isExtensionContext']
  const isMainWorldContext: typeof import('@/utils/utils')['isMainWorldContext']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const onlyExtensionGuard: typeof import('@/utils/js-context-guards')['onlyExtensionGuard']
  const onlyMainWorldGuard: typeof import('@/utils/js-context-guards')['onlyMainWorldGuard']
  const sleep: typeof import('@/utils/utils')['sleep']
  const t: typeof import('@complexity/i18n')['t']
  const use: typeof import('react')['use']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}