packages:
  - packages/*
  - packages/comctx-adapters/examples/*
  - perplexity/*
  - perplexity/extension/cli

catalogs:
  lint:
    eslint: ^9.39.2
    prettier: ^3.7.4
    typescript-eslint: ^8.52.0
  types:
    '@types/chrome': ^0.1.32
    typescript: ^5.9.3

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - spawn-sync
