packages:
  - packages/*
  - packages/comctx-adapters/examples/*
  - perplexity/*
  - perplexity/extension/cli

catalogs:
  lint:
    eslint: ^9.39.4
    prettier: ^3.8.2
    typescript-eslint: ^8.58.1
  types:
    '@types/chrome': ^0.1.40
    typescript: ^5.9.3

ignoredBuiltDependencies:
  - unrs-resolver

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - spawn-sync
