packages:
  - packages/*
  - packages/comctx-adapters/examples/*
  - perplexity/*
  - perplexity/extension/cli

catalogs:
  lint:
    eslint: 9.38.0
    prettier: ^3.6.2
    typescript-eslint: ^8.46.2
  types:
    '@types/chrome': ^0.1.27
    typescript: ^5.9.3

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - spawn-sync
