/**
 * Mixes of both native css and jquery selectors, so always use jQuery instead of document.querySelector
 */

import type { DomSelectors } from "@/services/cplx-api/versioned-remote-resources/dom-selectors/types";

export const DOM_SELECTORS: DomSelectors = {
  PAGE_WRAPPER: ".h-\\[100dvh\\]",
  PAGE_CHILD_WRAPPER: ".h-\\[100dvh\\] > [class^=erp][style^=padding]",
  SIDEBAR: {
    WRAPPER: ".group\\/sidebar",
    MOBILE_TRIGGER:
      ".h-headerHeight.absolute button:has(svg.tabler-icon-menu-2)",
  },
  THREAD: {
    /** The outermost container that wraps the thread container and the query box */
    NAVBAR: ".h-headerHeight.absolute",
    PAGE_WRAPPER: ".h-\\[100dvh\\] > .max-h-screen",
    WRAPPER: ".h-headerHeight.absolute + div",
    /** The container that wraps all messages */
    MESSAGE_BLOCKS_WRAPPER: {
      DESKTOP: {
        NORMAL: `.h-headerHeight.absolute + div > div > div:last-child`,
        BRANCHED: `.h-headerHeight.absolute + div > div > div:last-child`,
      },
      MOBILE: {
        NORMAL: `.h-headerHeight.absolute + div > div > div:last-child`,
        BRANCHED: `.h-headerHeight.absolute + div > div > div:last-child`,
      },
    },
    MESSAGE: {
      OUTER_WRAPPER: "div:not([class]),.erp-sidecar\\:pb-0.pb-16",
      INNER_WRAPPER: "> div > div > .bg-transparent",
      QUERY_WRAPPER: ".isolate.mx-auto > .max-w-threadContentWidth:first-child",
      QUERY: ".group\\/query",
      QUERY_EDIT_BUTTON_GROUP:
        ".absolute.bottom-0.right-0:not(.pointer-events-none)",
      QUERY_EDIT_BUTTON_GROUP_CHILD: {
        EDIT_QUERY_BUTTON: "button:has(svg[data-icon='pen-to-square'])",
      },
      STICKY_HEADER: ".h-headerHeight.absolute",
      SOURCES: ".gap-sm.grid.grid-cols-4.md\\:px-0",
      ANSWER: "div[id*='markdown-content-']",
      /** The bottom toolbar of the message (share, rewrite, model name, etc.) */
      FOOTER:
        ".gap-y-sm.md\\:gap-y-md.flex.flex-col > .flex.items-center.justify-between",
      FOOTER_CHILD: {
        REWRITE_BUTTON: "button:has(svg.tabler-icon-repeat)",
        COPY_BUTTON: "button[aria-label]:has(svg.tabler-icon-copy)",
        THUMBS_DOWN_BUTTON: "button:has(svg.tabler-icon-thumb-down)",
        MISC_BUTTON: "button:has(svg.tabler-icon-dots)",
      },
      IMAGE_GEN: {
        OPTIONS_GRID:
          "div.grid.grid-cols-2.gap-sm.border-borderMain\\/50.ring-borderMain\\/50.divide-borderMain\\/50.dark\\:divide-borderMainDark\\/50.dark\\:ring-borderMainDark\\/50.dark\\:border-borderMainDark\\/50.bg-transparent",
      },
      CODE_BLOCK: {
        /** The outermost container that wraps the pre & code block */
        WRAPPER: "div.w-full.md\\:max-w-\\[90vw\\]:has(>pre)",
        NATIVE_HEADER: ".codeWrapper>div:first-child",
        NATIVE_COPY_BUTTON: 'button[data-testid="copy-code-button"]',
      },
    },
    POPPER: {
      DESKTOP: ".duration-250.fill-mode-both>.absolute.left-0.right-0.top-0",
    },
  },
  HOME: {
    SLOGAN: ".mb-lg.md\\:absolute.text-center",
    FOOTER: ".hidden.pb-md.md\\:block>div",
    COMET_HOME_MAIN_WRAPPER:
      ".grid.grid-cols-\\[repeat\\(auto-fill\\,minmax\\(160px\\,1fr\\)\\)\\].gap-3",
  },
  QUERY_BOX: {
    WRAPPER: {
      MAIN: 'body[location="home"] .grow.block',
      SPACE: 'body[location="collection"] .grow.block',
      FOLLOW_UP: 'body[location="thread"] .grow.block',
      ARBITRARY: ".grow.block",
    },
    ATTR_WRAPPER: "> div > div > div",
    ATTR_WRAPPER_CHILD: {
      LEFT_ATTR_WRAPPER: ">div:nth-child(2)",
      RIGHT_ATTR_WRAPPER: ">div:nth-child(3)",
    },
    TEXTBOX: {
      MAIN: "#ask-input",
      SPACE: "#ask-input",
      FOLLOW_UP: "#ask-input",
      EDIT_QUERY: "div[contenteditable='true'][role='textbox']:not([id])",
      ARBITRARY: "#ask-input,div[contenteditable='true'][role='textbox']",
    },
    ATTACH_BUTTON: 'button:has([data-icon="paperclip"]):last',
    SUBMIT_BUTTON:
      'button[aria-label="Submit"], button[aria-label="Dictation"], button:has(svg.tabler-icon-square)',
    FORK_BUTTON: 'button svg[data-icon="code-fork"]',
    PRO_SEARCH_TOGGLE: "button#copilot-toggle",
    INCOGNITO_TOGGLE: ".mr-xs.flex.shrink-0.items-center",
    TYPEAHEAD_MENU: "#typeahead-menu",
    CONTENT_EDITABLE: {
      TEXTCONTENT_NODE: '[data-lexical-text="true"]',
    },
  },
  SETTINGS_PAGE: {
    SIDEBAR_WRAPPER: ".w-sideBarWidth, .scrollable-container",
    SIDEBAR_CHILD: {
      BACK_BUTTON: ".mb-3.ml-2.flex.md\\:px-2",
    },
  },
  STICKY_NAVBAR: ".h-headerHeight.absolute",
  SICKY_NAVBAR_CHILD: {
    THREAD_TITLE_WRAPPER:
      ".hidden.max-w-md.grow.items-center.justify-center.gap-x-xs.text-center.md\\:flex",
    THREAD_TITLE:
      ".min-w-0 .cursor-pointer.transition.duration-300.hover\\:opacity-70",
    THREAD_TITLE_INPUT: 'input[placeholder="Untitled"]',
    OVERFLOW_MENU_BUTTON_WRAPPER:
      "div:has(>span>button):has(svg.tabler-icon-dots)",
  },
} as const;

/**
 * Selectors that are generated by the extension.
 */
export const INTERNAL_ATTRIBUTES = {
  SIDEBAR: {
    WRAPPER: "sidebar-wrapper",
    MOBILE_TRIGGER: "sidebar-mobile-trigger",
  },
  HOME: {
    SLOGAN: "home-slogan",
    FOOTER: "home-footer",
    LANGUAGE_SELECTOR: "home-language-selector",
  },
  THREAD: {
    NAVBAR: "thread-navbar",
    NAVBAR_CHILD: {
      EXPORT_THREAD_BUTTON: "thread-export-button",
      OVERFLOW_MENU_BUTTON_WRAPPER: "thread-overflow-menu-button-wrapper",
    },
    PAGE_WRAPPER: "thread-page-wrapper",
    WRAPPER: "thread-wrapper",
    MESSAGE_BLOCKS_WRAPPER: "thread-message-blocks-wrapper",
    TOC_CONTAINER: "thread-toc-container",
    POPPER: {
      DESKTOP: "thread-popper-desktop",
    },
    MESSAGE: {
      BLOCK: "message-block",
      QUERY: "message-block-query",
      QUERY_EDIT_BUTTON_GROUP: "message-block-query-edit-button-group",
      ANSWER: "message-block-answer",
      CODE_BLOCK: "message-block-code-block",
      MIRRORED_CODE_BLOCK: "mirrored-code-block",
      FOOTER: "message-block-footer",
    },
    ATTACHMENT_DROP_ZONE: "drag-n-drop-file-to-upload",
  },
  QUERY_BOX_CHILD: {
    COMPONENTS_WRAPPER: "query-box-components-wrapper",
    PPLX_LEFT_TOOLBAR_COMPONENTS_WRAPPER:
      "query-box-pplx-left-toolbar-components-wrapper",
    CPLX_LEFT_TOOLBAR_COMPONENTS_LEFT_WRAPPER:
      "query-box-cplx-left-toolbar-components-left-wrapper",
    CPLX_LEFT_TOOLBAR_COMPONENTS_RIGHT_WRAPPER:
      "query-box-cplx-left-toolbar-components-right-wrapper",
    PPLX_RIGHT_TOOLBAR_COMPONENTS_WRAPPER:
      "query-box-pplx-right-toolbar-components-wrapper",
    CPLX_RIGHT_TOOLBAR_COMPONENTS_LEFT_WRAPPER:
      "query-box-cplx-right-toolbar-components-left-wrapper",
    CPLX_RIGHT_TOOLBAR_COMPONENTS_RIGHT_WRAPPER:
      "query-box-cplx-right-toolbar-components-right-wrapper",
  },
  SPACES_PAGE: {
    SPACE_CARD: "space-card",
  },
  SETTINGS_PAGE: {
    SIDEBAR_WRAPPER: "settings-page-sidebar-wrapper",
    CPLX_DASHBOARD_LINK: "settings-page-cplx-dashboard-link",
  },
} as const;

export const TEST_ID = {
  QUERY_BOX: {
    FOCUS_SELECTOR: "cplx-focus-selector",
    LANGUAGE_MODEL_SELECTOR: "cplx-language-model-selector",
    IMAGE_GEN_MODEL_SELECTOR: "cplx-image-gen-model-selector",
    SPACE_NAVIGATOR: "cplx-space-navigator",
  },
} as const;
