export const pplxLocalLanguageModels = [
  {
    label: "Claude 4 Sonnet",
    shortLabel: "Sonnet",
    code: "claude2",
    provider: "Anthropic",
    limitKey: "gpt4_limit",
    type: "fast",
    hideFromList: false,
  },
  {
    label: "Claude 4 Sonnet",
    shortLabel: "Sonnet Thinking",
    code: "claude37sonnetthinking",
    provider: "Anthropic",
    limitKey: "gpt4_limit",
    type: "reasoning",
    hideFromList: false,
  },
  {
    label: "Claude 4 Opus",
    shortLabel: "Opus Thinking",
    code: "claude4opusthinking",
    provider: "Anthropic",
    limitKey: "gpt4_limit",
    type: "reasoning",
    hideFromList: false,
  },
  {
    label: "Gemini 2.5 Pro",
    shortLabel: "Gemini Pro",
    code: "gemini2flash",
    provider: "Google",
    limitKey: "gpt4_limit",
    type: "fast",
    hideFromList: false,
  },
  {
    label: "o3",
    shortLabel: "o3",
    code: "o3",
    provider: "OpenAI",
    limitKey: "gpt4_limit",
    type: "reasoning",
    hideFromList: false,
  },
  {
    label: "o4 Mini",
    shortLabel: "o4 Mini",
    code: "o4mini",
    provider: "OpenAI",
    limitKey: "gpt4_limit",
    type: "reasoning",
    hideFromList: false,
  },
  {
    label: "DeepSeek R1 (1776)",
    shortLabel: "R1",
    code: "r1",
    provider: "DeepSeek",
    limitKey: "gpt4_limit",
    type: "reasoning",
    hideFromList: false,
  },
  {
    label: "GPT-4.1",
    shortLabel: "GPT-4.1",
    code: "gpt41",
    provider: "OpenAI",
    limitKey: "gpt4_limit",
    type: "fast",
    hideFromList: false,
  },
  {
    label: "Grok-3 Beta",
    shortLabel: "Grok-3",
    code: "grok",
    provider: "xAI",
    limitKey: "gpt4_limit",
    type: "fast",
    hideFromList: false,
  },
  {
    label: "Deep Research",
    shortLabel: "Deep Research",
    code: "pplx_alpha",
    provider: "PerplexityDeepResearch",
    limitKey: "gpt4_limit",
    type: "deepResearch",
    hideFromList: false,
  },
  {
    label: "Labs",
    shortLabel: "Labs",
    code: "pplx_beta",
    provider: "PerplexityLabs",
    limitKey: "pplx_beta_limit",
    type: "deepResearch",
    hideFromList: false,
  },
  {
    label: "Sonar",
    shortLabel: "Sonar",
    code: "experimental",
    provider: "Perplexity",
    limitKey: "gpt4_limit",
    type: "fast",
    hideFromList: false,
  },
  {
    label: "Auto",
    shortLabel: "Auto",
    code: "pplx_pro",
    provider: "Perplexity",
    type: "auto",
    hideFromList: true,
  },
] as const;
